import { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
			<body>
				<main>{children}</main>
			</body>
		</html>
	)
}
